function(target_all_warnings target visibility)
  if(MSVC)
    target_compile_options(${target} ${visibility} /W4)
  elseif(CMAKE_COMPILER_IS_GNUCC OR CMAKE_COMPILER_IS_GNUCXX)
    target_compile_options(${target} ${visibility} -Wall -Wextra -Wno-long-long -pedantic)
  endif()    
endfunction(target_all_warnings)

function(target_warnings_are_errors target visibility)
  if(MSVC)
    target_compile_options(${target} ${visibility} /WX)
  elseif(CMAKE_COMPILER_IS_GNUCC OR CMAKE_COMPILER_IS_GNUCXX)
    target_compile_options(${target} ${visibility} -Werror)
  endif()    
endfunction(target_warnings_are_errors)