function(target_all_warnings target)
    if(MSVC)
        target_compile_options(${target} PRIVATE /W4)
    elseif(CMAKE_COMPILER_IS_GNUCC OR CMAKE_COMPILER_IS_GNUCXX)
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wno-long-long -pedantic)
    endif()    
endfunction(target_all_warnings)

function(target_warnings_are_errors target)
    if(MSVC)
        target_compile_options(${target} PRIVATE /WX)
    elseif(CMAKE_COMPILER_IS_GNUCC OR CMAKE_COMPILER_IS_GNUCXX)
        target_compile_options(${target} PRIVATE -Werror)
    endif()    
endfunction(target_warnings_are_errors)